#!/usr/bin/env python
"""build_review_bundle.py - assemble a per-task review bundle + MANIFEST.md + zip.

The change-tracking mechanism (I-21). Spec-driven and task-agnostic: point it at a
JSON spec listing scripts, DB objects, registry rows, artefacts, deletions and
acceptance criteria, and it produces a self-describing bundle under
Output/review_bundles/<tier>_<task>/ and a zip beside it.

MANIFEST.md records, so a reviewer never has to reconstruct state:
  - scripts touched, each with git tracked/committed/dirty status + last commit
  - DB objects created, each with row count + the CREATE SQL from sqlite_master
  - registry rows, each with id + checksum + path_exists
  - artefacts copied, each with byte size
  - anything deleted (from the spec)
  - each acceptance criterion, marked met with the number that shows it

Usage:  python scripts/utils/build_review_bundle.py <spec.json>
"""
import hashlib
import csv
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DB = ROOT / "Output" / "database" / "Gayini_Results.sqlite"
BIG_BYTES = 10 * 1024 * 1024   # artefacts above this are REFERENCED (path+checksum),
                               # not copied - a small bundle gets read more than a big one.


def sha256_first50(path):
    """First-50-MB SHA-256 - the project's asset checksum convention."""
    cap, h = 50 * 1024 * 1024, hashlib.sha256()
    with open(path, "rb") as f:
        rem = cap
        while rem > 0:
            b = f.read(min(1024 * 1024, rem))
            if not b:
                break
            h.update(b)
            rem -= len(b)
    return h.hexdigest()


def git(*args):
    try:
        return subprocess.run(["git", "-C", str(ROOT), *args],
                              capture_output=True, text=True).stdout.strip()
    except Exception as e:
        return f"(git error: {e})"


def script_status(rel):
    tracked = git("ls-files", "--error-unmatch", rel) != ""
    if not tracked:
        return "UNTRACKED", "-"
    last = git("log", "-1", "--format=%h %ad %s", "--date=short", "--", rel)
    dirty = git("status", "--porcelain", "--", rel) != ""
    return ("MODIFIED (uncommitted changes)" if dirty else "committed"), last


def human(n):
    n = float(n)
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:.0f} {u}" if u == "B" else f"{n:.1f} {u}"
        n /= 1024


def main(spec_path):
    spec = json.loads(Path(spec_path).read_text(encoding="utf-8"))
    task, tier = spec["task"], spec.get("tier", "tier")
    bundle = ROOT / "Output" / "review_bundles" / f"{tier}_{task}"
    if bundle.exists():
        shutil.rmtree(bundle)
    (bundle / "code").mkdir(parents=True)
    (bundle / "outputs").mkdir()
    (bundle / "reports").mkdir()
    (bundle / "tables").mkdir()

    con = sqlite3.connect(f"file:{DB.as_posix()}?mode=ro", uri=True)
    L = ["# Review bundle - " + task, "", f"Tier: {tier}  ·  DB: `{DB.relative_to(ROOT)}`",
         "", "_Generated by build_review_bundle.py. Numbers re-derived from the DB at "
         "bundle time; re-run to refresh._", ""]
    if spec.get("headline"):
        L += ["> " + str(spec["headline"]).replace("\n", "\n> "), ""]

    # ---- scripts ----
    L += ["## Scripts touched", "", "| script | git status | last commit |", "|---|---|---|"]
    for rel in spec.get("scripts", []):
        src = ROOT / rel
        st, last = script_status(rel)
        L.append(f"| `{rel}` | {st} | {last or '-'} |")
        if src.is_file():
            dst = bundle / "code" / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    L.append("")

    # ---- DB objects ----
    L += ["## DB objects created", "", "| object | type | rows | creating SQL (first line) |",
          "|---|---|---|---|"]
    for name in spec.get("db_objects", []):
        row = con.execute(
            "SELECT type, sql FROM sqlite_master WHERE name=?", (name,)).fetchone()
        if row is None:
            L.append(f"| `{name}` | MISSING | - | - |")
            continue
        typ, sql = row
        try:
            n = con.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]
        except Exception:
            n = "-"
        first = (sql or "").strip().splitlines()[0][:80]
        L.append(f"| `{name}` | {typ} | {n} | `{first}...` |")
    # full CREATE SQL appendix
    L += ["", "<details><summary>Full CREATE statements</summary>", "", "```sql"]
    for name in spec.get("db_objects", []):
        r = con.execute("SELECT sql FROM sqlite_master WHERE name=?", (name,)).fetchone()
        if r and r[0]:
            L.append(r[0].strip() + ";")
    L += ["```", "</details>", ""]

    # ---- DB table exports (CSV from the live DB, so a reviewer needs no SQLite) ----
    exports = spec.get("db_exports", [])
    if exports:
        L += ["## DB table exports (CSV under `tables/`)", "",
              "_Exported from the live DB at bundle time; a reviewer sees the data without SQLite._",
              "", "| file | query | rows |", "|---|---|---|"]
        for ex in exports:
            q, fn = ex["query"], ex["file"]
            cur = con.execute(q)
            cols = [d[0] for d in cur.description]
            data = cur.fetchall()
            with open(bundle / "tables" / fn, "w", newline="", encoding="utf-8") as fh:
                w = csv.writer(fh); w.writerow(cols); w.writerows(data)
            note = "" if "expect" not in ex or len(data) == ex["expect"] else f" (expected {ex['expect']}!)"
            L.append(f"| `tables/{fn}` | `{q}` | {len(data)}{note} |")
        L.append("")

    # ---- registry rows ----
    L += ["## Registry rows", "", "| table | id | checksum | path_exists |",
          "|---|---|---|---|"]
    for reg in spec.get("registry", []):
        tbl, rid = reg["table"], reg["id"]
        idcol = tbl + "_id"
        try:
            r = con.execute(
                f"SELECT checksum_sha256, path_exists FROM {tbl} WHERE {idcol}=?",
                (rid,)).fetchone()
            if r:
                L.append(f"| {tbl} | `{rid}` | `{(r[0] or '')[:16]}` | {r[1]} |")
            else:
                L.append(f"| {tbl} | `{rid}` | MISSING | - |")
        except Exception as e:
            L.append(f"| {tbl} | `{rid}` | (err {e}) | - |")
    L.append("")

    # ---- artefacts ----  (small = copied; large = referenced by path + checksum)
    L += ["## Artefacts", "",
          f"_Files over {BIG_BYTES // (1024*1024)} MB are referenced by path + first-50-MB "
          "SHA-256, not copied, to keep the bundle small._", "",
          "| artefact | size | in bundle | checksum (first-50MB sha256) |",
          "|---|---|---|---|"]
    seen = set()
    for pat in spec.get("artefacts", []):
        for src in sorted(ROOT.glob(pat)):
            if not src.is_file() or src in seen:
                continue
            seen.add(src)
            rel = src.relative_to(ROOT).as_posix()
            sz = src.stat().st_size
            if sz > BIG_BYTES:
                L.append(f"| `{rel}` | {human(sz)} | referenced (not copied) | "
                         f"`{sha256_first50(src)[:16]}` |")
            else:
                sub = "reports" if src.suffix == ".md" else "outputs"
                shutil.copy2(src, bundle / sub / src.name)
                L.append(f"| `{rel}` | {human(sz)} | copied | - |")
    L.append("")

    # ---- deletions ----
    L += ["## Deleted", ""]
    dels = spec.get("deletions", [])
    L += ([f"- `{d}`" for d in dels] if dels else ["_none_"]) + [""]

    # ---- acceptance ----
    L += ["## Acceptance criteria", "", "| criterion | evidence | met |", "|---|---|---|"]
    for a in spec.get("acceptance", []):
        crit = a["criterion"]
        ev, met = a.get("note", ""), "yes"
        if "query" in a:
            try:
                val = con.execute(a["query"]).fetchone()[0]
                ev = f"{a.get('note','')} = **{val}**".strip(" =")
                if "expect" in a:
                    met = "yes" if str(val) == str(a["expect"]) else "**NO**"
            except Exception as e:
                ev, met = f"query error: {e}", "**NO**"
        L.append(f"| {crit} | {ev} | {met} |")
    L.append("")

    con.close()
    (bundle / "MANIFEST.md").write_text("\n".join(L), encoding="utf-8")

    # ---- zip ----
    zpath = bundle.parent / f"{tier}_{task}.zip"
    if zpath.exists():
        zpath.unlink()
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for p in bundle.rglob("*"):
            if p.is_file():
                z.write(p, p.relative_to(bundle.parent))
    n_files = sum(1 for _ in bundle.rglob("*") if _.is_file())
    print(f"bundle: {bundle.relative_to(ROOT)}  ({n_files} files)")
    print(f"zip   : {zpath.relative_to(ROOT)}  ({human(zpath.stat().st_size)})")
    print(f"manifest: {(bundle / 'MANIFEST.md').relative_to(ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: build_review_bundle.py <spec.json>")
    main(sys.argv[1])
