## -----------------------------------------------------------------------------
## Gayini remote sensing workflow
## 07h_plot_annual_inundation_panels_v2.R
## -----------------------------------------------------------------------------


## Purpose:
## Create improved annual inundation panels and annual source-density summaries.
## Uses annual rasters generated by Step 07e; does not rebuild rasters.


## User settings ----

root_dir <- normalizePath("D:/Github_repos/Gayini", winslash = "/", mustWork = TRUE)


## Required packages ----

required_packages <- c(
  "sf",
  "terra",
  "dplyr",
  "tidyr",
  "readr",
  "stringr",
  "purrr",
  "ggplot2",
  "magrittr"
)

source(file.path(root_dir, "R", "step7_figure_helpers.R"))
gayini_check_packages(required_packages)

library(sf)
library(terra)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(purrr)
library(ggplot2)
library(magrittr)


## Paths ----

annual_dir <- file.path(root_dir, "Output", "rasters", "inundation_pre_post", "annual")
figure_dir <- file.path(root_dir, "Output", "figures", "07h_annual_inundation_panels_v2")
diagnostics_dir <- file.path(root_dir, "Output", "diagnostics", "step7_figure_luts")

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(diagnostics_dir, recursive = TRUE, showWarnings = FALSE)

observation_density_path <- gayini_find_first_existing(c(
  file.path(root_dir, "Output", "diagnostics", "07e_pre_post_inundation_observation_density_by_year.csv"),
  file.path(root_dir, "Output", "diagnostics", "07f_pre_post_inundation_observation_density_by_year.csv")
))


## Spatial context ----

context <- gayini_load_plot_context(root_dir)
plots_sf <- context$plots_sf
boundary_sf <- context$boundary_sf
zones_sf <- context$zones_sf


## Annual raster catalogue ----

annual_files <- list.files(
  annual_dir,
  pattern = "^annual_inundated_any_.*\\.tif$",
  full.names = TRUE
)

if (length(annual_files) == 0) {
  stop("No annual_inundated_any rasters found in: ", annual_dir, call. = FALSE)
}

annual_tbl <- tibble::tibble(file_path = annual_files) %>%
  dplyr::mutate(file_name = basename(.data$file_path)) %>%
  tidyr::extract(
    .data$file_name,
    into = c("prefix", "period", "analysis_year"),
    regex = "^(annual_inundated_any)_(pre_conservation|post_conservation)__([0-9]{4})\\.tif$",
    remove = FALSE
  ) %>%
  dplyr::mutate(
    analysis_year = as.integer(.data$analysis_year),
    period_year = paste0(.data$period, "__", .data$analysis_year),
    period_label = dplyr::case_when(
      .data$period == "pre_conservation" ~ "Pre-conservation",
      .data$period == "post_conservation" ~ "Post-conservation",
      TRUE ~ .data$period
    )
  ) %>%
  dplyr::arrange(.data$period, .data$analysis_year)

if (!is.na(observation_density_path)) {
  observation_density <- readr::read_csv(observation_density_path, show_col_types = FALSE) %>%
    dplyr::select(dplyr::any_of(c("period_year", "n_rasters_total", "n_unique_dates", "n_sentinel2_rasters", "n_landsat_rasters", "observation_density_class")))

  annual_tbl <- annual_tbl %>%
    dplyr::left_join(observation_density, by = "period_year")
} else {
  annual_tbl <- annual_tbl %>%
    dplyr::mutate(
      n_rasters_total = NA_integer_,
      observation_density_class = "density_unknown"
    )
}


## Calculate annual wet-area percent ----

annual_summary <- annual_tbl %>%
  dplyr::mutate(
    wet_area_pct = purrr::map_dbl(
      .data$file_path,
      function(path) {
        r <- terra::rast(path)
        as.numeric(terra::global(r, mean, na.rm = TRUE)[1, 1]) * 100
      }
    ),
    facet_label = paste0(
      "WY", .data$analysis_year,
      "\nwet = ", sprintf("%.0f", .data$wet_area_pct), "%",
      "\nrasters = ", dplyr::coalesce(as.character(.data$n_rasters_total), "?"),
      "\n", dplyr::coalesce(.data$observation_density_class, "density_unknown")
    )
  )

annual_summary_path <- file.path(figure_dir, "07h_annual_inundation_summary_v2.csv")
readr::write_csv(annual_summary, annual_summary_path)
message("Wrote: ", annual_summary_path)


## Function to make period raster panel ----

make_period_panel <- function(period_value) {
  use_tbl <- annual_summary %>%
    dplyr::filter(.data$period == !!period_value) %>%
    dplyr::arrange(.data$analysis_year)

  if (nrow(use_tbl) == 0) {
    warning("No annual rasters found for period: ", period_value, call. = FALSE)
    return(invisible(NULL))
  }

  panel_df <- purrr::map_dfr(seq_len(nrow(use_tbl)), function(i) {
    r <- terra::rast(use_tbl$file_path[[i]])

    gayini_raster_to_df(r, "annual_inundated_any") %>%
      dplyr::mutate(
        period = use_tbl$period[[i]],
        analysis_year = use_tbl$analysis_year[[i]],
        facet_label = use_tbl$facet_label[[i]]
      )
  })

  ref_r <- terra::rast(use_tbl$file_path[[1]])
  target_crs <- sf::st_crs(terra::crs(ref_r))

  boundary_r <- if (!is.null(boundary_sf)) sf::st_transform(boundary_sf, target_crs) else NULL
  zones_r <- if (!is.null(zones_sf)) sf::st_transform(zones_sf, target_crs) else NULL
  plots_r <- sf::st_transform(plots_sf, target_crs)

  title_prefix <- dplyr::case_when(
    period_value == "pre_conservation" ~ "Pre-conservation",
    period_value == "post_conservation" ~ "Post-conservation",
    TRUE ~ period_value
  )

  p <- ggplot2::ggplot() +
    ggplot2::geom_raster(data = panel_df, ggplot2::aes(x = .data$x, y = .data$y, fill = factor(.data$annual_inundated_any))) +
    ggplot2::scale_fill_manual(
      values = c("0" = "#f0e7d6", "1" = "#3182bd"),
      na.value = "grey92",
      name = "Annual\ninundated",
      labels = c("0" = "No", "1" = "Yes")
    ) +
    {if (!is.null(zones_r)) ggplot2::geom_sf(data = zones_r, fill = NA, colour = "grey65", linewidth = 0.15)} +
    {if (!is.null(boundary_r)) ggplot2::geom_sf(data = boundary_r, fill = NA, colour = "black", linewidth = 0.3)} +
    ggplot2::geom_sf(data = plots_r, fill = NA, colour = "black", linewidth = 0.08) +
    ggplot2::facet_wrap(~ facet_label, ncol = 3) +
    ggplot2::coord_sf(expand = FALSE) +
    ggplot2::labs(
      title = paste0(title_prefix, " annual inundation occurrence rasters"),
      subtitle = "annual_inundated_any = wet at least once in the water year. Facets show farm-wide wet area and source density."
    ) +
    gayini_theme_map(base_size = 11)

  out_path <- file.path(figure_dir, paste0("07h_annual_inundated_any_", period_value, "_panel_v2.png"))
  ggplot2::ggsave(out_path, plot = p, width = 12.5, height = 8.5, dpi = 300)
  message("Wrote: ", out_path)

  invisible(out_path)
}

make_period_panel("pre_conservation")
make_period_panel("post_conservation")


## Annual wet-area timeseries ----

wet_area_plot <- ggplot2::ggplot(
  annual_summary,
  ggplot2::aes(
    x = .data$analysis_year,
    y = .data$wet_area_pct,
    colour = .data$period_label,
    group = .data$period_label
  )
) +
  ggplot2::geom_line(linewidth = 0.7) +
  ggplot2::geom_point(size = 2.5) +
  ggplot2::scale_x_continuous(breaks = sort(unique(annual_summary$analysis_year))) +
  ggplot2::labs(
    title = "Farm-wide annual inundated area by water year",
    subtitle = "Calculated from annual_inundated_any rasters. Values are percent of valid cells marked wet.",
    x = "Water year",
    y = "Wet area (%)",
    colour = "Period"
  ) +
  gayini_theme_chart(base_size = 12)

wet_area_path <- file.path(figure_dir, "07h_annual_wet_area_percent_timeseries.png")
ggplot2::ggsave(wet_area_path, plot = wet_area_plot, width = 10, height = 5.8, dpi = 300)
message("Wrote: ", wet_area_path)


## Observation density summary ----

if ("n_rasters_total" %in% names(annual_summary)) {
  density_plot <- ggplot2::ggplot(
    annual_summary,
    ggplot2::aes(
      x = factor(.data$analysis_year),
      y = .data$n_rasters_total,
      fill = .data$observation_density_class
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::labs(
      title = "Inundation source-raster density by water year",
      subtitle = "Higher post-period density, especially from Sentinel-2, may increase detection of short-lived water.",
      x = "Water year",
      y = "Number of selected rasters",
      fill = "Density class"
    ) +
    gayini_theme_chart(base_size = 12)

  density_path <- file.path(figure_dir, "07h_annual_observation_density_summary.png")
  ggplot2::ggsave(density_path, plot = density_plot, width = 10, height = 5.8, dpi = 300)
  message("Wrote: ", density_path)
}


message("07h v2 complete. Wrote outputs to: ", figure_dir)
