param(
  [string]$Root = (Resolve-Path ".").Path
)

$ErrorActionPreference = "Stop"

function ConvertTo-RepoPath {
  param([string]$Path)
  return ($Path -replace "\\", "/").TrimStart("./")
}

function Escape-Markdown {
  param([string]$Text)
  return ($Text -replace "\|", "\|")
}

function Get-Classification {
  param(
    [string]$RelativePath,
    [string]$Extension,
    [bool]$Referenced,
    [bool]$DeckReferenced,
    [bool]$Latest
  )

  $pathLower = $RelativePath.ToLowerInvariant()
  $fileName = [System.IO.Path]::GetFileName($RelativePath).ToLowerInvariant()

  if ($pathLower -match "^output/_archive/") {
    return @("local_archive", "keep_local_archive", "Local archive created by approved cleanup; retained for traceability.")
  }

  $canonicalOutputs = @(
    "output/csv/04c_fractional_cover_full.csv",
    "output/csv/05c_landsat_inundation_full.csv",
    "output/csv/06c_daily_inundation_full.csv",
    "output/csv/07f_pre_post_inundation_plot_summary_fixed.csv",
    "output/csv/curated_ground_cover_timeseries.csv",
    "output/csv/curated_annual_inundation_timeseries.csv",
    "output/csv/curated_daily_inundation_monthly.csv",
    "output/csv/plot_rs_analysis_base.csv",
    "output/csv/10a_ground_cover_prepost_plot_summary.csv",
    "output/csv/10a_ground_cover_prepost_group_summary.csv",
    "output/csv/10a_ground_cover_prepost_model_summary.csv"
  )

  if ($canonicalOutputs -contains $pathLower) {
    return @("current_canonical", "keep_current", "Named canonical output in current docs/run-order.")
  }

  if ($pathLower -match "^output/rasters/mer/") {
    return @("current_mer_raster_product", "keep_current", "MER raster product folder; do not delete automatically.")
  }

  if ($pathLower -match "^output/rasters/inundation_pre_post/") {
    return @("current_canonical", "keep_current", "Canonical pre/post inundation raster product.")
  }

  if ($pathLower -match "^output/csv/mer/" -or $pathLower -match "^output/reports/mer/") {
    return @("current_mer_report_or_table", "keep_current", "Current MER table/report output.")
  }

  if ($pathLower -match "^output/figures/review/mer/" -or $pathLower -match "^output/figures/06_mer_inundation/") {
    return @("current_review_deck_asset", "keep_current", "MER review/deck figure asset.")
  }

  if ($DeckReferenced -or $pathLower -match "^output/figures/review/" -or $pathLower -match "^output/reports/adrian_review_png_assets/") {
    return @("current_review_deck_asset", "keep_current", "Current review/deck asset or referenced by deck register.")
  }

  if ($pathLower -match "^output/packages/" -or $pathLower -match "ppt_asset_pack" -or $pathLower -match "package" -or $Extension -match "^\.(zip|7z)$") {
    return @("local_package_bundle", "move_to_local_archive", "Package/task bundle artifact; keep local or archive outside handoff.")
  }

  if ($pathLower -match "^output/reports/output_audit/") {
    return @("current_handoff_report", "keep_local_only", "Generated by this output audit; ignored by Git.")
  }

  if ($pathLower -match "^output/reports/repo_acceptance/" -or $pathLower -match "^output/reports/spine_smoke_test/" -or $pathLower -match "^output/reports/code_refresh/") {
    return @("current_handoff_report", "keep_local_only", "Local validation/handoff report; useful but generated.")
  }

  if ($pathLower -match "manifest|register|copy_log|asset_register|inventory|spine") {
    return @("current_manifest_or_register", "keep_supporting", "Manifest/register supports traceability.")
  }

  if ($pathLower -match "^output/diagnostics/") {
    if ($pathLower -match "05b_|04a_|04b_|05a_|06a_|06b_|test_|archive") {
      return @("legacy_old_diagnostic", "manual_review", "Older diagnostic naming; review before deletion.")
    }
    return @("current_diagnostic", "keep_local_only", "Diagnostic output for QA/reproducibility.")
  }

  if ($pathLower -match "^output/csv/") {
    if ($fileName -match "^(04a_|04b_|05a_|06a_|06b_|07e_|test_)") {
      return @("legacy_superseded", "manual_review", "Older/dev CSV output; review against current replacement.")
    }
    if ($Referenced) {
      return @("current_supporting", "keep_supporting", "CSV is referenced by active code/docs/registers.")
    }
    return @("manual_review", "manual_review", "CSV role is unclear from references.")
  }

  if ($pathLower -match "^output/figures/") {
    if ($pathLower -match "04a_|04b_|05a_|06a_|06b_|07e_|test_") {
      return @("legacy_old_deck_asset", "manual_review", "Older/dev figure output; review before deletion.")
    }
    return @("current_supporting", "keep_supporting", "Figure output outside current deck register.")
  }

  if ($pathLower -match "^output/reports/") {
    if ($pathLower -match "task_|code_audit|archive_dry_run|old|superseded") {
      return @("legacy_task_output", "move_to_local_archive", "Older task/audit report; keep local archive if needed.")
    }
    return @("current_supporting", "keep_supporting", "Report output.")
  }

  if ($Latest -eq $false -and $Referenced -eq $false) {
    return @("safe_to_delete_candidate", "delete_after_review", "Older unreferenced member of an output family.")
  }

  return @("manual_review", "manual_review", "No confident classification rule matched.")
}

$outputRoot = Join-Path $Root "Output"
$reportDir = Join-Path $outputRoot "reports/output_audit"
New-Item -ItemType Directory -Force -Path $reportDir | Out-Null

$branch = (& git -C $Root branch --show-current).Trim()
$head = (& git -C $Root rev-parse HEAD).Trim()
$status = (& git -C $Root status --short --branch) -join "`n"
$generatedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$gitStatusReport = @(
  "# Stage 6 git status report",
  "",
  "Generated: $generatedAt",
  "",
  "- Starting branch: refactor/stage5-repo-acceptance-audit-20260628",
  "- New branch: $branch",
  "- Latest commit: $head",
  "- Branch push status: branch pushed before major edits",
  "- Output status: Output/ is ignored by Git; audit reports are local generated files",
  "- Known local-only item: tbreak/ remains untracked and untouched",
  "",
  '```text',
  $status,
  '```'
)
$gitStatusReport -join "`n" | Set-Content -Encoding UTF8 -Path (Join-Path $Root "Output/reports/output_audit/stage6_git_status_report.md")

$rawOutputPaths = [System.IO.Directory]::GetFiles($outputRoot, "*", [System.IO.SearchOption]::AllDirectories)
$outputFiles = $rawOutputPaths |
  Where-Object { [System.IO.File]::Exists($_) } |
  ForEach-Object { [System.IO.FileInfo]::new($_) } |
  Sort-Object FullName
$repoTextRoots = @("R", "scripts", "docs", "tools", "tests")
$repoTextFiles = @()
foreach ($dir in $repoTextRoots) {
  $full = Join-Path $Root $dir
  if (Test-Path $full) {
    $repoTextFiles += (& rg --files $dir) |
      ForEach-Object { Get-Item -LiteralPath (Join-Path $Root $_) } |
      Where-Object { $_.Extension -match "^\.(R|r|ps1|py|md|csv|txt|json|yml|yaml|Rmd)$" }
  }
}
foreach ($file in @("README.md", "run_spine_smoke_test.R", "DESCRIPTION", ".gitignore")) {
  $full = Join-Path $Root $file
  if (Test-Path $full) { $repoTextFiles += Get-Item $full }
}

$referenceRows = @()
$referencePattern = "Output[/\\][A-Za-z0-9_\- .()/\\]+"
foreach ($file in ($repoTextFiles | Sort-Object FullName -Unique)) {
  $relFile = ConvertTo-RepoPath ($file.FullName.Substring($Root.Length).TrimStart("\", "/"))
  $lines = Get-Content -Path $file.FullName -ErrorAction SilentlyContinue
  for ($i = 0; $i -lt $lines.Count; $i++) {
    $matches = [regex]::Matches($lines[$i], $referencePattern)
    foreach ($match in $matches) {
      $outPath = ($match.Value -replace "\\", "/").TrimEnd(".", ",", ";", ":", ")", "]", "}", "'", '"')
      $type = "unknown"
      if ($relFile -like "scripts/*" -or $relFile -like "R/*") {
        if ($lines[$i] -match "write|dir.create|output|created_by|save|ggsave") { $type = "script_output" }
        elseif ($lines[$i] -match "read|file.exists|input|Expected") { $type = "script_input" }
        else { $type = "unknown" }
      } elseif ($relFile -like "docs/run_order/*") {
        $type = "run_order_reference"
      } elseif ($relFile -like "tests/*") {
        $type = "test_reference"
      } elseif ($relFile -eq "run_spine_smoke_test.R") {
        $type = "spine_check_reference"
      } else {
        $type = "doc_reference"
      }
      $referenceRows += [pscustomobject]@{
        output_path              = $outPath
        referenced_in            = $relFile
        reference_type           = $type
        line_number_if_available = $i + 1
        context                  = $lines[$i].Trim()
        reference_status         = $(if (Test-Path (Join-Path $Root $outPath)) { "exists" } else { "missing_or_pattern" })
        notes                    = ""
      }
    }
  }
}

$registerFiles = $outputFiles |
  Where-Object { $_.Name -match "(manifest|asset_register|copy_log|register|inventory|spine)" -and $_.Extension -match "^\.(csv|md|txt|json|ndjson)$" }

foreach ($file in $registerFiles) {
  $relFile = ConvertTo-RepoPath ($file.FullName.Substring($Root.Length).TrimStart("\", "/"))
  $lines = Get-Content -Path $file.FullName -ErrorAction SilentlyContinue
  for ($i = 0; $i -lt $lines.Count; $i++) {
    $matches = [regex]::Matches($lines[$i], $referencePattern)
    foreach ($match in $matches) {
      $outPath = ($match.Value -replace "\\", "/").TrimEnd(".", ",", ";", ":", ")", "]", "}", "'", '"')
      $referenceRows += [pscustomobject]@{
        output_path              = $outPath
        referenced_in            = $relFile
        reference_type           = $(if ($relFile -match "asset_register") { "asset_register_reference" } else { "register_reference" })
        line_number_if_available = $i + 1
        context                  = $lines[$i].Trim()
        reference_status         = $(if (Test-Path (Join-Path $Root $outPath)) { "exists" } else { "missing_or_pattern" })
        notes                    = "Reference found inside Output register/manifest."
      }
    }
  }
}

$referenceRows = $referenceRows | Sort-Object output_path, referenced_in, line_number_if_available -Unique
$referenceRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_reference_index.csv")

$referencedSet = @{}
$deckReferencedSet = @{}
$docReferencedSet = @{}
$scriptReferencedSet = @{}
$registerReferencedSet = @{}
foreach ($row in $referenceRows) {
  $key = $row.output_path.ToLowerInvariant()
  $referencedSet[$key] = $true
  if ($row.reference_type -eq "asset_register_reference") { $deckReferencedSet[$key] = $true }
  if ($row.reference_type -eq "doc_reference" -or $row.reference_type -eq "run_order_reference") { $docReferencedSet[$key] = $true }
  if ($row.reference_type -match "^script_") { $scriptReferencedSet[$key] = $true }
  if ($row.reference_type -match "register") { $registerReferencedSet[$key] = $true }
}

$familyGroups = @{}
foreach ($file in $outputFiles) {
  $rel = ConvertTo-RepoPath ($file.FullName.Substring($Root.Length).TrimStart("\", "/"))
  $dir = ConvertTo-RepoPath (Split-Path $rel -Parent)
  $stem = [System.IO.Path]::GetFileNameWithoutExtension($rel).ToLowerInvariant()
  $stem = $stem -replace "_?\d{8}(_\d{6})?", ""
  $stem = $stem -replace "_?2026\d{4}(_\d{6})?", ""
  $family = "$dir/$stem"
  if (-not $familyGroups.ContainsKey($family)) { $familyGroups[$family] = @() }
  $familyGroups[$family] += $file
}

$latestByFamily = @{}
foreach ($family in $familyGroups.Keys) {
  $latest = $familyGroups[$family] | Sort-Object LastWriteTime -Descending | Select-Object -First 1
  $latestByFamily[(ConvertTo-RepoPath ($latest.FullName.Substring($Root.Length).TrimStart("\", "/"))).ToLowerInvariant()] = $true
}

$inventoryRows = @()
foreach ($file in $outputFiles) {
  $rel = ConvertTo-RepoPath ($file.FullName.Substring($Root.Length).TrimStart("\", "/"))
  $parts = $rel -split "/"
  $folder = if ($parts.Count -gt 1) { $parts[1] } else { "" }
  $subfolder = if ($parts.Count -gt 2) { ($parts[2..([Math]::Min($parts.Count - 2, 4))] -join "/") } else { "" }
  $ext = $file.Extension.ToLowerInvariant()
  $key = $rel.ToLowerInvariant()
  $latest = $latestByFamily.ContainsKey($key)
  $class = Get-Classification -RelativePath $rel -Extension $ext -Referenced:$referencedSet.ContainsKey($key) -DeckReferenced:$deckReferencedSet.ContainsKey($key) -Latest:$latest
  $inventoryRows += [pscustomobject]@{
    path                              = $file.FullName
    relative_path                     = $rel
    folder                            = $folder
    subfolder                         = $subfolder
    filename                          = $file.Name
    extension                         = $ext
    file_size_bytes                   = $file.Length
    modified_time                     = $file.LastWriteTime.ToString("s")
    created_time_if_available         = $file.CreationTime.ToString("s")
    depth                             = ($parts.Count - 1)
    is_empty                          = $file.Length -eq 0
    is_large_file                     = $file.Length -ge 52428800
    is_raster                         = $ext -match "^\.(tif|tiff|vrt|aux\.xml)$"
    is_figure                         = $ext -match "^\.(png|jpg|jpeg|svg)$"
    is_csv                            = $ext -eq ".csv"
    is_report                         = $ext -match "^\.(md|html|pdf|docx|pptx|xlsx)$"
    is_diagnostic                     = $rel.ToLowerInvariant() -match "/diagnostics/"
    is_package_or_bundle              = $rel.ToLowerInvariant() -match "packages|ppt_asset_pack|package|\.zip$|\.7z$"
    is_manifest                       = $file.Name.ToLowerInvariant() -match "manifest|register|copy_log|inventory|spine"
    is_handoff                        = $file.Name.ToLowerInvariant() -match "handoff"
    is_current_candidate              = $class[0] -match "^current_"
    referenced_by_register            = $registerReferencedSet.ContainsKey($key)
    referenced_by_script              = $scriptReferencedSet.ContainsKey($key)
    referenced_by_doc                 = $docReferencedSet.ContainsKey($key)
    referenced_by_deck_asset_register = $deckReferencedSet.ContainsKey($key)
    latest_with_same_stem             = $latest
    classification                    = $class[0]
    recommended_action                = $class[1]
    reason                            = $class[2]
    manual_review_required            = $class[0] -match "manual_review" -or $class[1] -match "manual_review|delete_after_review"
    notes                             = ""
  }
}

$inventoryRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_file_inventory.csv")
$inventoryRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_classification.csv")

$familyRows = foreach ($family in ($familyGroups.Keys | Sort-Object)) {
  $files = $familyGroups[$family] | Sort-Object LastWriteTime -Descending
  $latest = $files | Select-Object -First 1
  $latestRel = ConvertTo-RepoPath ($latest.FullName.Substring($Root.Length).TrimStart("\", "/"))
  $older = @($files | Select-Object -Skip 1 | ForEach-Object { ConvertTo-RepoPath ($_.FullName.Substring($Root.Length).TrimStart("\", "/")) })
  [pscustomobject]@{
    family_id                         = $family
    file_count                        = $files.Count
    latest_file                       = $latestRel
    latest_modified_time              = $latest.LastWriteTime.ToString("s")
    current_canonical_file            = $(if (($inventoryRows | Where-Object { $_.relative_path -eq $latestRel }).classification -match "^current_") { $latestRel } else { "" })
    older_files                       = ($older -join "; ")
    recommended_action_for_older_files = $(if ($older.Count -gt 0) { "manual_review_or_archive_older_unreferenced" } else { "not_applicable" })
    notes                             = ""
  }
}
$familyRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_family_latest_index.csv")

$handoffRows = $inventoryRows | Where-Object {
  $_.classification -match "current_canonical|current_supporting|current_review_deck_asset|current_mer_raster_product|current_mer_report_or_table|current_manifest_or_register|current_handoff_report"
} | Select-Object @{n="path";e={$_.relative_path}},
  @{n="category";e={$_.classification}},
  @{n="why_keep";e={$_.reason}},
  @{n="used_by";e={ if ($_.referenced_by_deck_asset_register) { "deck_asset_register" } elseif ($_.referenced_by_script) { "active_script" } elseif ($_.referenced_by_doc) { "docs" } elseif ($_.referenced_by_register) { "register" } else { "classification_rule" } }},
  @{n="safe_to_share";e={ if ($_.classification -match "local_|diagnostic") { "review_first" } else { "yes" } }},
  @{n="large_file";e={$_.is_large_file}},
  @{n="notes";e={$_.notes}}
$handoffRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "current_handoff_output_set.csv")

$cleanupRows = $inventoryRows | Where-Object {
  $_.classification -ne "local_archive" -and (
    $_.classification -match "^legacy_|^local_|safe_to_delete_candidate|manual_review" -or
    $_.recommended_action -match "move_to_local_archive|delete|manual_review"
  )
} | Select-Object @{n="path";e={$_.relative_path}},
  classification,
  recommended_action,
  reason,
  @{n="referenced_anywhere";e={$referencedSet.ContainsKey($_.relative_path.ToLowerInvariant())}},
  @{n="latest_replacement";e={
    $dir = ConvertTo-RepoPath (Split-Path $_.relative_path -Parent)
    $stem = [System.IO.Path]::GetFileNameWithoutExtension($_.relative_path).ToLowerInvariant()
    $stem = $stem -replace "_?\d{8}(_\d{6})?", ""
    $stem = $stem -replace "_?2026\d{4}(_\d{6})?", ""
    $family = "$dir/$stem"
    if ($familyGroups.ContainsKey($family)) {
      ConvertTo-RepoPath (($familyGroups[$family] | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName.Substring($Root.Length).TrimStart("\", "/"))
    } else {
      ""
    }
  }},
  manual_review_required,
  @{n="risk_level";e={
    if ($_.referenced_by_script -or $_.referenced_by_deck_asset_register -or $_.is_raster) { "high" }
    elseif ($_.manual_review_required -or $_.referenced_by_doc -or $_.referenced_by_register) { "medium" }
    else { "low" }
  }},
  notes
$cleanupRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_cleanup_candidates.csv")

$structureMd = @(
  "# Proposed Output Structure",
  "",
  "Generated: $generatedAt",
  "",
  "Do not immediately change script output paths. Current scripts expect stable",
  "folders such as `Output/csv/`, `Output/figures/review/`, `Output/reports/`,",
  "`Output/diagnostics/`, and `Output/rasters/`.",
  "",
  "Recommended near-term policy:",
  "",
  '```text',
  "Output/",
  "  csv/                    # stable canonical/supporting tables",
  "  figures/                # current figures; review deck figures under review/",
  "  rasters/                # current raster products; MER rasters under MER/",
  "  diagnostics/            # local QA diagnostics, retained locally",
  "  reports/                # local reports and audit outputs",
  "  packages/               # local-only task bundles; archive or delete after review",
  "  _archive/               # future local archive for old outputs, ignored by Git",
  '```',
  "",
  "Use the registers created by this audit to define the current handoff set rather",
  "than moving files now. A future controlled task can move legacy/package outputs",
  "to `Output/_archive/` after review."
)
$structureMd -join "`n" | Set-Content -Encoding UTF8 -Path (Join-Path $reportDir "proposed_output_structure.md")

$totalSize = ($inventoryRows | Measure-Object -Property file_size_bytes -Sum).Sum
$byFolder = $inventoryRows | Group-Object folder | Sort-Object Name
$byClass = $inventoryRows | Group-Object classification | Sort-Object Name

$handoffMd = @()
$handoffMd += "# Stage 6 Output Audit Handoff"
$handoffMd += ""
$handoffMd += "Generated: $generatedAt"
$handoffMd += ""
$handoffMd += "## Summary"
$handoffMd += ""
$handoffMd += "- Branch: $branch"
$handoffMd += "- Commit status: pending final Stage 6 commit at report creation"
$handoffMd += "- Output files audited: $($inventoryRows.Count)"
$handoffMd += "- Total Output size bytes: $totalSize"
$handoffMd += "- Current handoff output set: Output/reports/output_audit/current_handoff_output_set.csv"
$handoffMd += "- Cleanup candidates: Output/reports/output_audit/output_cleanup_candidates.csv"
$handoffMd += "- No files were deleted or moved by this audit."
$handoffMd += ""
$handoffMd += "## Counts by folder"
$handoffMd += ""
foreach ($g in $byFolder) { $handoffMd += "- $($g.Name): $($g.Count)" }
$handoffMd += ""
$handoffMd += "## Counts by classification"
$handoffMd += ""
foreach ($g in $byClass) { $handoffMd += "- $($g.Name): $($g.Count)" }
$handoffMd += ""
$handoffMd += "## Recommendations"
$handoffMd += ""
$handoffMd += "- Keep current canonical CSVs, current MER reports/tables/rasters, and deck-register assets."
$handoffMd += "- Treat Output/packages and ppt asset packs as local-only archive candidates."
$handoffMd += "- Keep diagnostics locally for QA, but do not expose them as current handoff outputs unless specifically needed."
$handoffMd += "- Review manual-review and delete-after-review candidates before any cleanup execution."
$handoffMd += "- Do not run destructive cleanup in this task."
$handoffMd += ""
$handoffMd += "## Recommended Task 20"
$handoffMd += ""
$handoffMd += "Review `output_cleanup_candidates.csv`, approve a low-risk subset, then run the cleanup dry-run again before any `-Execute` cleanup."
$handoffMd -join "`n" | Set-Content -Encoding UTF8 -Path (Join-Path $reportDir "stage6_output_audit_handoff.md")

$summaryRows = $byClass | ForEach-Object {
  [pscustomobject]@{
    classification = $_.Name
    file_count = $_.Count
    total_size_bytes = (($_.Group | Measure-Object -Property file_size_bytes -Sum).Sum)
  }
}
$summaryRows | Export-Csv -NoTypeInformation -Path (Join-Path $reportDir "output_classification_summary.csv")
